### PR TITLE
Added SendImage support

### PR DESCRIPTION
**Pull request by kitzler-walli**
I updated the js-api and added a SendImage functionality to your code.

### CODE REVIEW

**Comment by dotWee** [comment]
> I updated the js-api and added a SendImage functionality to your code.

Since the [matrix sender node](https://github.com/mlopezr/node-red-contrib-matrixbot/pull/8/files#diff-cc50239fdd41da0da546c7131bb9616da17ad9b47f130258fe64c7150198a579R150-R151) now accepts `msg.payload.content`, `msg.payload.raw`, `msg.payload.imgType` & `msg.payload.text`, could you provide an example injection? Not sure about the new parameters, except `msg.payload.text`.

**Comment by kitzler-walli** [comment]
This is how I use it in a function node before sending it to the bot:
```
let img = msg.payload;
//msg.payload = flow.get('payload');
msg.payload = {};
msg.payload.content = img;
msg.payload.raw = false;
msg.payload.imgType = 'image/jpeg';
msg.payload.type = "image";
return msg;
```

**Comment by dotWee** [comment]
Got it running and it works like a charm, thanks! Your implementation is really appreciated!

**Comment by kitzler-walli** [comment]
I'll probably add encryption support next

**Comment by dotWee** [comment]
Maybe think about releasing your contributions as an active fork, since this repo sadly seems unmaintained.

**Comment by yousefamar** [comment]
@mlopezr If you no longer wish to maintain this package, would you mind making @kitzler-walli a maintainer on both GitHub and npm? @kitzler-walli would you be open to that? If not, I would be happy to do it on your behalf (my npm username is `amar`).

If @mlopezr is AWOL, then @kitzler-walli would you be willing to publish your fork on npm under a different name so that it shows up in the palette search? I think it will take over quickly when you look at the dates.

Then in the future, others won't be in my situation where I found out about the fork after having started to replicate the work @kitzler-walli has already done. @kitzler-walli, unless you've already started E2EE support, I'll PR to your fork for now once I've finished that.

**Comment by mlopezr** [comment]
Thanks so much for the pull request @kitzler-walli, I have merged it and published a new version on npm.

It's great to see people using and improving this!

I haven't used Matrix or NodeRed in a while so I can't maintain this repo any more. As per @yousefamar's suggestion, I've invited @kitzler-walli to become maintainer on GitHub, and I can do it for npm as well if you give me your login.

**Comment by kitzler-walli** [comment]
My username at npm is kitzler_walli

**Pull request merged**
